// Scoring and output rendering.

// Waived checks are reported but left out of the score entirely, rather than
// counted as passes — a team that opts out of a check should not be rewarded
// for it, and inflating the number would make the grade meaningless.
const VALUE = { pass: 1, warn: 0.5, fail: 0 };
const MARK = { pass: "PASS", warn: "WARN", fail: "FAIL", waived: "WAIV", na: "N/A " };
const COLOR = { pass: "\x1b[32m", warn: "\x1b[33m", fail: "\x1b[31m", waived: "\x1b[90m", na: "\x1b[90m" };
const RESET = "\x1b[0m";

export function score(results) {
  const scored = results.filter((r) => r.status in VALUE);
  const total = scored.reduce((sum, r) => sum + r.weight, 0);
  const earned = scored.reduce((sum, r) => sum + r.weight * VALUE[r.status], 0);
  return total ? Math.round((earned / total) * 100) : 100;
}

export function grade(value) {
  if (value >= 90) return "A";
  if (value >= 80) return "B";
  if (value >= 65) return "C";
  if (value >= 50) return "D";
  return "F";
}

const VERDICT = {
  A: "Agents can work here unsupervised on well-scoped tasks.",
  B: "Agents work here, but reviewers still catch avoidable mistakes.",
  C: "Agents produce plausible code that nothing in this repo can verify.",
  D: "Most agent output here needs a human rewrite before it merges.",
  F: "Agents are guessing. Expect confident, unverifiable pull requests.",
};

export function renderTerminal(results, { color = true } = {}) {
  const value = score(results);
  const letter = grade(value);
  const paint = (status, text) => (color ? `${COLOR[status]}${text}${RESET}` : text);
  const lines = ["", `  Agent readiness: ${value}/100  (${letter})`, `  ${VERDICT[letter]}`, ""];

  for (const r of results) {
    lines.push(`  ${paint(r.status, MARK[r.status].padEnd(4))}  ${r.title}`);
    lines.push(`        ${r.detail}`);
    if (r.fix) lines.push(`        -> ${r.fix}`);
  }

  const count = (status) => results.filter((r) => r.status === status).length;
  const tail = [
    count("waived") ? `${count("waived")} waived` : null,
    count("na") ? `${count("na")} not applicable` : null,
  ].filter(Boolean);
  lines.push(
    "",
    `  ${count("fail")} failing, ${count("warn")} warning, ${count("pass")} passing` + (tail.length ? `, ${tail.join(", ")}` : ""),
    "",
  );
  return lines.join("\n");
}

export function renderMarkdown(results, { repo = "this repository" } = {}) {
  const value = score(results);
  const letter = grade(value);
  const icon = { pass: "✅", warn: "⚠️", fail: "❌", waived: "➖", na: "➖" };
  const lines = [
    `# Agent readiness: ${value}/100 (${letter})`,
    "",
    `_${VERDICT[letter]}_`,
    "",
    `Audited \`${repo}\` against ${results.length} checks.`,
    "",
    "| | Check | Finding |",
    "|---|---|---|",
  ];
  for (const r of results) {
    lines.push(`| ${icon[r.status]} | ${r.title} | ${r.detail.replace(/\|/g, "\\|")} |`);
  }

  const actionable = results.filter((r) => r.fix);
  if (actionable.length) {
    lines.push("", "## What to fix, in order", "");
    const order = { fail: 0, warn: 1, pass: 2, waived: 3, na: 4 };
    for (const r of [...actionable].sort((a, b) => order[a.status] - order[b.status] || b.weight - a.weight)) {
      lines.push(`- **${r.title}** — ${r.fix}`);
    }
  }
  lines.push("", "<sub>Generated by agentready.</sub>");
  return lines.join("\n");
}

export function renderJson(results, { repo } = {}) {
  const value = score(results);
  return JSON.stringify(
    {
      repo,
      score: value,
      grade: grade(value),
      verdict: VERDICT[grade(value)],
      checks: results.map(({ id, title, weight, status, detail, fix }) => ({ id, title, weight, status, detail, fix: fix ?? null })),
    },
    null,
    2,
  );
}
